### ISSUE TITLE
URL not found avr-gcc-7.3.0-atmel3.6.1-azduino7b-aarch64-pc-linux-gnu.tar.bz2

### ISSUE THREAD

**Issue by Nuts-Underline** [SpenceKonde/ReleaseScripts#43]
URL not found
https://spencekondetoolchains.s3.amazonaws.com/avr-gcc-7.3.0-atmel3.6.1-azduino7b-aarch64-pc-linux-gnu.tar.bz2
in
https://github.com/SpenceKonde/ReleaseScripts/blob/master/package_drazzy.com_index.json
result:

<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
avr-gcc-7.3.0-atmel3.6.1-azduino7b-aarch64-pc-linux-gnu.tar.bz2
</Key>

**Comment by SpenceKonde** [comment]
Should be fixed, somehow 2 of the actual archives had lost their gnu in the filename.... You might have to delete the json file in your Arduino15 folder to force it to refresh. I know it can cache it but not for how long.

**Comment by Nuts-Underline** [comment]
Nop! You fixed "version": "7.3.0-atmel3.6.1-azduino7b"
but actual version "version": "7.3.0-atmel3.6.1-azduino7b1"
still having
https://spencekondetoolchains.s3.amazonaws.com/avr-gcc-7.3.0-atmel3.6.1-azduino7b-aarch64-pc-linux-gnu.tar.bz2
even not azduino**7b1**

**Comment by SpenceKonde** [comment]
Should be good now. 

Also added in avrdude 7.2 to the json file, it will begin being used in future releases.

**Comment by MCUdude** [comment]
@SpenceKonde I've created a crude bash script that adds the next available Avrdude version to the boards manager script.
I've messed up so many times manually copying and pasting URLs, file sizes, and checksums, so a script, even a crude one, is way better.

https://github.com/MCUdude/MightyCore/blob/gh-pages/Add_avrdude_release.sh

Now that you're going to use Avrdude 7.2, are you going to use it for SerialUPDI uploads as well?

FYI Avrdue 7.3 is going to be a blast. Now it finally has support for the tricky Arduino Leonardo/micro "1200bps touch" reset method, but my favorite new feature is undoubtedly the way you can deal with serial ports. Instead of always having to use the COM port number (or /dev/* on macOS/Linux), you can use their USB vid/pid and serial number (if necessary), or simply their name if present in avrdude.conf, which they likely are if you're using a fairly standard USB to serial adapter:

```
$ ./avrdude -curclock -patmega328p -P dunno
avrdude OS error: cannot open port dunno: No such file or directory
avrdude error: unable to open programmer urclock on port dunno
Possible candidate serial ports are:
  -P /dev/cu.Bluetooth-Incoming-Port
  -P /dev/cu.SLAB_USBtoUART or -P cp210x
  -P /dev/cu.UC-232AC or -P usb:0557:2008
  -P /dev/cu.usbmodem142201 or -P nano-every
  -P /dev/cu.usbmodem142301 or -P usb:2341:0043
  -P /dev/cu.usbmodem1424202 or -P usb:03eb:2145
  -P /dev/cu.usbmodem1424402 or -P usb:03eb:2175
  -P /dev/cu.usbserial-142140 or -P ch340
Note that above ports might not be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.

avrdude done.  Thank you.
```

from avrdude.conf
```
[...]

#------------------------------------------------------------
# ch340
#------------------------------------------------------------

serialadapter # ch340
    id                     = "ch340";
    desc                   = "WCH CH340 USB to serial adapter";
    usbvid                 = 0x1a86;
    usbpid                 = 0x7523;
;

#------------------------------------------------------------
# ch9102
#------------------------------------------------------------

serialadapter # ch9102
    id                     = "ch9102";
    desc                   = "WCH CH9102 USB to serial adapter";
    usbvid                 = 0x1a86;
    usbpid                 = 0x55d4;
;

#------------------------------------------------------------
# cp210x
#------------------------------------------------------------

serialadapter # cp210x
    id                     = "cp210x";
    desc                   = "Silabs CP210x USB to serial adapter";
    usbvid                 = 0x10c4;
    usbpid                 = 0xea60, 0xea70, 0xea71;
;

[...]
```

**Comment by Nuts-Underline** [comment]
heh, good  question, but i missed this problem for this time. I having curiosity nano for UDPI, so going to check about it

**Comment by SpenceKonde** [comment]
That sounds useful, assuming we're actually able to use avrdude 7.2,  though that's contingent on basic functionality working, and that's not what I'm seeing...
